### RabbitMQ config
# Biến khớp với start.sh
max_message_size = 536870912
consumer_timeout = 86400000

### Minio config
# Biến khớp với start.sh: MINIO__ACCESS_KEY, MINIO__SECRET_KEY
MINIO_ROOT_USER=opencti
MINIO_ROOT_PASSWORD=Vipstmt@828682
MINIO_VOLUMES="/var/lib/minio/data"
MINIO_OPTS="--console-address :9001"

### Redis config
# Biến khớp với start.sh: REDIS__PORT=6379, REDIS__PASSWORD=****
bind 0.0.0.0
port 6379
dir /var/lib/redis
daemonize no
loglevel notice
logfile /var/log/redis/redis.log
# Persistence
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
# Authentication (from start.sh REDIS__PASSWORD)
requirepass Vipstmt@828682