# MinIO Configuration
# This file is sourced by v2_start_minio.sh and minio.service
# Owner: admin:admin

MINIO_USER="admin"
MINIO_GROUP="admin"
MINIO_ROOT_USER="opencti"
MINIO_ROOT_PASSWORD="Vipstmt@828682"
MINIO_VOLUMES="/var/lib/minio/data"
MINIO_OPTS="--console-address :9001"