# Logrotate cho OpenCTI Platform
/var/log/v2-ti/opencti/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 100M
}

# Logrotate cho OpenCTI Worker
/var/log/v2-ti/opencti-worker/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 100M
}

# Logrotate cho Elasticsearch
/var/log/v2-ti/elasticsearch/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 200M
}

# Logrotate cho RabbitMQ
/var/log/v2-ti/rabbitmq/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 100M
}
