elasticsearch:
  url: http://localhost:8686
  index_prefix: opencti

telegram:
  # bot_token: "8760411583:AAEaMSvoiwvZT8gyDRiHS2djR7ZegbxFI9M"
  # chat_id: "-1003831445471"
  bot_token: "5135556010:AAF-KCuJw7gSCOg0pOQIHkfg1DIsD2pql3U"
  chat_id: "-1002999135889"
  format: both  # "table" (PC), "text" (điện thoại), "both" (gửi cả 2)
